#!/bin/bash
# lib/install.sh — user questions, stage3 download, stage3 extraction, portage setup

ask_user_info() {
    log_section "Installation Configuration"

    ask_input HOSTNAME "Hostname" "gentoo"
    ask_input USERNAME "Username" "user"
    ask_input TIMEZONE "Timezone (e.g. Europe/Kyiv)" "Europe/Kyiv"

    echo ""
    echo -e "${CYAN}Root password:${NC}"
    read -rs ROOT_PASSWORD; echo ""
    echo -e "${CYAN}Confirm root password:${NC}"
    read -rs ROOT_PASSWORD2; echo ""
    [[ "$ROOT_PASSWORD" == "$ROOT_PASSWORD2" ]] || die "Root passwords do not match"
    [[ -n "$ROOT_PASSWORD" ]] || die "Root password cannot be empty"

    echo ""
    echo -e "${CYAN}Password for user '${USERNAME}':${NC}"
    read -rs USER_PASSWORD; echo ""
    echo -e "${CYAN}Confirm password:${NC}"
    read -rs USER_PASSWORD2; echo ""
    [[ "$USER_PASSWORD" == "$USER_PASSWORD2" ]] || die "User passwords do not match"
    [[ -n "$USER_PASSWORD" ]] || die "User password cannot be empty"

    echo ""
    log_info "Hostname : $HOSTNAME"
    log_info "Username : $USERNAME"
    log_info "Timezone : $TIMEZONE"

    export HOSTNAME USERNAME TIMEZONE ROOT_PASSWORD USER_PASSWORD
}

download_stage3() {
    log_section "Downloading Gentoo Stage3 (OpenRC)"

    local base_url="https://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-openrc"
    local list_url="${base_url}/latest-stage3-amd64-openrc.txt"

    log_step "Fetching latest stage3 release info..."
    local stage3_entry
    stage3_entry=$(curl -sf "$list_url" | grep -v '^#' | grep '\.tar\.' | head -1) \
        || die "Failed to fetch stage3 index from: $list_url"

    # Format: "20241201T164440Z/stage3-amd64-openrc-20241201T164440Z.tar.xz  SIZE  CHECKSUM"
    local stage3_path
    stage3_path=$(awk '{print $1}' <<< "$stage3_entry")
    STAGE3_FILE="$(basename "$stage3_path")"
    STAGE3_URL="${base_url}/${stage3_path}"

    log_step "Latest stage3: ${STAGE3_FILE}"

    local dest="/tmp/${STAGE3_FILE}"
    if [[ -f "$dest" ]]; then
        log_warn "Archive already cached at $dest — skipping download"
    else
        log_step "Downloading (this may take several minutes)..."
        wget --progress=bar:force -O "$dest" "$STAGE3_URL" \
            || die "Failed to download stage3 from: $STAGE3_URL"
    fi

    # Verify SHA256 (from the DIGESTS file)
    log_step "Verifying SHA256 checksum..."
    local digests_file="/tmp/${STAGE3_FILE}.DIGESTS"
    if wget -q -O "$digests_file" "${STAGE3_URL}.DIGESTS" 2>/dev/null; then
        local expected_sha256 actual_sha256
        # DIGESTS format: "SHA256\n<hash>  <filename>\n..."
        expected_sha256=$(awk '/^SHA256/{getline; print $1; exit}' "$digests_file" 2>/dev/null || true)
        if [[ -n "$expected_sha256" ]]; then
            actual_sha256=$(sha256sum "$dest" | awk '{print $1}')
            if [[ "$expected_sha256" == "$actual_sha256" ]]; then
                log_info "Checksum OK"
            else
                die "SHA256 mismatch — download may be corrupt. Delete /tmp/${STAGE3_FILE} and retry."
            fi
        else
            log_warn "Could not parse SHA256 from DIGESTS, skipping verification"
        fi
    else
        log_warn "Could not download DIGESTS file, skipping checksum verification"
    fi

    STAGE3_DEST="$dest"
    export STAGE3_FILE STAGE3_URL STAGE3_DEST
}

extract_stage3() {
    log_section "Extracting Stage3 -> ${MOUNTPOINT}"

    log_step "Extracting ${STAGE3_FILE}..."
    tar xpf "$STAGE3_DEST" \
        --xattrs-include='*.*' \
        --numeric-owner \
        -C "$MOUNTPOINT" \
        || die "Failed to extract stage3"

    log_info "Stage3 extracted"
}

generate_fstab() {
    log_section "Generating /etc/fstab"

    local fstab="${MOUNTPOINT}/etc/fstab"
    local uuid_root uuid_swap
    uuid_root=$(blkid -s UUID -o value "$PART_ROOT")
    uuid_swap=$(blkid -s UUID -o value "$PART_SWAP")

    local root_opts="defaults,relatime,errors=remount-ro"
    [[ "$DISK_TYPE" == "ssd" ]] && root_opts="defaults,relatime,discard,errors=remount-ro"

    cat > "$fstab" << EOF
# /etc/fstab — generated by gentoo-installer
# <device>                                <mp>       <fs>    <options>             <dump> <pass>
UUID=${uuid_root}  /          ext4    ${root_opts}  0      1
UUID=${uuid_swap}  none       swap    sw                    0      0
EOF

    if [[ -n "${PART_EFI:-}" ]]; then
        local uuid_efi
        uuid_efi=$(blkid -s UUID -o value "$PART_EFI")
        echo "UUID=${uuid_efi}  /boot/efi  vfat    defaults,noatime              0      2" >> "$fstab"
    fi

    log_step "Generated fstab:"
    cat "$fstab"
}

setup_portage() {
    log_section "Configuring Portage"

    local portage_dir="${MOUNTPOINT}/etc/portage"
    local nproc
    nproc=$(nproc)
    # Use nproc+1 for -j to keep CPU saturated during I/O stalls
    local njobs=$(( nproc + 1 ))

    # ── make.conf ──────────────────────────────────────────────────────
    log_step "Writing make.conf (march=${CPU_MARCH}, j=${njobs})..."
    cat > "${portage_dir}/make.conf" << EOF
# /etc/portage/make.conf — generated by gentoo-installer
# Target: Lenovo IdeaPad Slim 3 15ABR8 (Ryzen 5 7430U / Zen 3)

# ── Compiler ───────────────────────────────────────────────────────────
CFLAGS="-march=${CPU_MARCH} -O2 -pipe"
CXXFLAGS="\${CFLAGS}"
FCFLAGS="\${CFLAGS}"
FFLAGS="\${CFLAGS}"

# ── Parallelism ────────────────────────────────────────────────────────
MAKEOPTS="-j${njobs} -l${nproc}"

# ── GPU ───────────────────────────────────────────────────────────────
VIDEO_CARDS="${VIDEO_CARDS}"
INPUT_DEVICES="libinput"

# ── USE flags ─────────────────────────────────────────────────────────
# Global USE flags — profile default/linux/amd64/23.0/desktop/plasma
# adds kde, plasma, X automatically; we extend with Wayland + audio stack.
USE="wayland elogind openrc -systemd pipewire bluetooth networkmanager
     alsa -pulseaudio vulkan vaapi dbus policykit udev acl xattr
     -gnome -gtk -handbook -test"

# ── Licenses ──────────────────────────────────────────────────────────
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

# ── Binary packages (minimises compile time!) ─────────────────────────
# Official Gentoo binary host — pre-built for amd64/23.0 profile
BINHOSTS="https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/"
EMERGE_DEFAULT_OPTS="--getbinpkg --binpkg-respect-use=y --ask=n --jobs=${njobs}"
BINPKG_FORMAT="gpkg"
FEATURES="parallel-fetch buildpkg getbinpkg"

# ── Mirrors ────────────────────────────────────────────────────────────
GENTOO_MIRRORS="https://distfiles.gentoo.org"

# ── Localisation ───────────────────────────────────────────────────────
L10N="en uk"
LINGUAS="en uk"
EOF

    # ── repos.conf ─────────────────────────────────────────────────────
    log_step "Writing repos.conf..."
    mkdir -p "${portage_dir}/repos.conf"
    cat > "${portage_dir}/repos.conf/gentoo.conf" << 'EOF'
[DEFAULT]
main-repo = gentoo

[gentoo]
location   = /var/db/repos/gentoo
sync-type  = rsync
sync-uri   = rsync://rsync.gentoo.org/gentoo-portage
auto-sync  = yes
sync-rsync-verify-jobs         = 1
sync-rsync-verify-metamanifest = yes
EOF

    # ── package.use ────────────────────────────────────────────────────
    log_step "Writing package.use overrides..."
    mkdir -p "${portage_dir}/package.use"
    cat > "${portage_dir}/package.use/installer" << EOF
# PipeWire — full backend support
media-video/pipewire     alsa bluetooth dbus jack pipewire-alsa sound-server v4l -systemd
media-libs/wireplumber   elogind -systemd

# KDE Plasma — Wayland + elogind (no systemd)
kde-plasma/plasma-workspace  wayland elogind -systemd
kde-plasma/kwin              wayland -systemd
kde-plasma/kscreenlocker     -systemd
kde-plasma/sddm-kcm          -systemd
kde-plasma/plasma-desktop    wayland
kde-plasma/powerdevil        -systemd

# SDDM — elogind backend
x11-misc/sddm    elogind -systemd

# NetworkManager — no systemd, wifi support
net-misc/networkmanager    -systemd elogind wifi wext

# GRUB — both EFI and PC support built in
sys-boot/grub:2    grub_platforms_efi-64 grub_platforms_pc

# Mesa — Vulkan + VA-API for AMD (RDNA 2 iGPU on Ryzen 5 7430U)
media-libs/mesa    vulkan vaapi xa ${GPU_USE_FLAGS}

# dracut — needed to build initramfs for binary kernel
sys-kernel/dracut    dracut

# elogind — OpenRC specific
sys-auth/elogind    -systemd openrc pam
EOF

    # ── package.accept_keywords ────────────────────────────────────────
    log_step "Writing package.accept_keywords..."
    mkdir -p "${portage_dir}/package.accept_keywords"
    cat > "${portage_dir}/package.accept_keywords/installer" << 'EOF'
# Pre-built kernel — accept ~amd64 for latest kernels
sys-kernel/gentoo-kernel-bin  ~amd64
sys-kernel/linux-firmware     ~amd64
# dracut for initramfs
sys-kernel/dracut             ~amd64
EOF

    # ── Propagate DNS into chroot ───────────────────────────────────────
    cp /etc/resolv.conf "${MOUNTPOINT}/etc/resolv.conf"

    log_info "Portage configured"
}
